<a href="https://colab.research.google.com/github/wilmanAQ/Inteligencia_Artificial/blob/IA/Clase_segundo_corte_panda_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa de Ingeneria em Sistemas

### Asignatura Inteligencia Artificial
<p style="font-size:23px; color:gray; text-align:false;">

<b>Grupo:</b> IS08N1.

<b>Created by:</b> Msc. Wilman Andrés Quiñonez V.
</p>

<div style="display: flex; justify-content: space-between; align-items: center">
  <img src="https://github.com/wilmanAQ/Inteligencia_Artificial/blob/IA/icono_unipacifico.jpeg?raw=1" width="100">
  <img src="https://github.com/wilmanAQ/Inteligencia_Artificial/blob/IA/icono_PIS.png?raw=1" width="270">
</div>

<b>Libreria Pandas- </b>Programa de Ingenería de Sistemas<b>.

# Introducción a Pandas

## 1. ¿Qué es Pandas?

Pandas es una librería de Python muy usada para análisis y manipulación de datos.

El nombre viene de Panel Data, un término en estadística.

Está construida sobre NumPy, lo que le da velocidad y soporte para operaciones matemáticas.

👉 En palabras simples:
# Pandas nos permite  (leer, organizar, limpiar, transformar y analizar datos)

## 2. ¿Cuándo usamos Pandas?

Usamos Pandas principalmente cuando necesitamos:

- Leer datos de archivos como **CSV, Excel, SQL, JSON, etc.**

- Limpiar datos **(valores faltantes, duplicados, formatos).**

- **Seleccionar y filtrar filas y columnas.**

- **Transformar datos (crear nuevas columnas, aplicar funciones).**

- **Analizar datos (estadísticas, agrupaciones, conteo, promedios).**

- **Visualizar datos en conjunto con librerías como Matplotlib o Seaborn.**

## ***Material de estudio**

- Link, documentación oficial de pandas:
  - https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#pandas-data-table-representation

  - https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#pandas-data-table-representation

  - https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html

In [5]:
import pandas as pd

## Representación de la tabla de datos de pandas

<div style="display: flex; justify-content: space-between; align-items: center">
  <img src="https://github.com/wilmanAQ/Inteligencia_Artificial/blob/IA/Tabla_pandas.png?raw=1" width="500">
  
</div>

In [7]:
df = pd.DataFrame(
      {
       "Name": [
               "Braund, Mr. Owen Harris",
                "Allen, Mr. William Henry",
               "Bonnell, Miss. Elizabeth",
         ],
           "Age": [22, 35, 58],
           "Sex": ["male", "male", "female"],
        }
   )



df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

## 3. Estructuras principales de Pandas

## Una estructura importante de pandas son las series, esta representan las ** columnas**
 - Solo me interesa trabajar con los datos de la columna

<div style="display: flex; justify-content: space-between; align-items: center">
  <img src="https://github.com/wilmanAQ/Inteligencia_Artificial/blob/IA/serie_panda.png?raw=1" width="200">
  
</div>

In [11]:
import pandas as pd

serie = pd.Series([10, 20, 30, 40], name="Edades")
print(serie)

0    10
1    20
2    30
3    40
Name: Edades, dtype: int64

Una DataFramees una estructura de datos bidimensional que puede almacenar datos de diferentes tipos **(incluyendo caracteres, enteros, valores de punto flotante, datos categóricos, etc.)** en columnas. Es similar a una hoja de cálculo, una tabla de SQL o la data.framede R.

La tabla tiene tres columnas, cada una con una etiqueta. Las etiquetas de columna son, respectivamente Name, , Agey Sex.

La columna Name consta de datos texto donde cada valor es una cadena, la columna Age son números y la columna Sex son datos textos.

En un software de hojas de cálculo, la representación de nuestros datos en forma de tabla se vería muy similar:

## ** Ejemplo**

<div style="display: flex; justify-content: space-between; align-items: center">
  <img src="https://github.com/wilmanAQ/Inteligencia_Artificial/blob/IA/tabla.png?raw=1" width="600">
  
</div>

In [21]:

#Construcción de series a partir de un diccionario con un índice especificado
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'b', 'c'])
ser

a    1
b    2
c    3
dtype: int64

In [22]:
#Las claves del diccionario coinciden con los valores del índice, por lo tanto, los valores del índice no tienen efecto.
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['x', 'y', 'z'])
ser

x   NaN
y   NaN
z   NaN
dtype: float64

In [23]:
r = [1, 2]
ser = pd.Series(r, copy=False)
ser.iloc[0] = 999
r
[1, 2]
ser

0    999
1      2
dtype: int64

In [28]:
import numpy as np
r = np.array([1, 2])
ser = pd.Series(r, copy=False)
ser.iloc[0] = 999
print("Array :", r)
print("------------")
print("Serie :", ser)

Array : [999   2]
------------
Serie : 0    999
1      2
dtype: int64

In [31]:
#Para crear una serie con un índice personalizado y ver las etiquetas del índice:

cities = ['Kolkata', 'Chicago', 'Toronto', 'Lisbon']
populations = [14.85, 2.71, 2.93, 0.51]
city_series = pd.Series(populations, index=cities)
city_series.index

Index(['Kolkata', 'Chicago', 'Toronto', 'Lisbon'], dtype='object')

In [33]:
#Para cambiar las etiquetas de índice de una serie existente:
city_series.index = ['KOL', 'CHI', 'TOR', 'LIS']
city_series.index

Index(['KOL', 'CHI', 'TOR', 'LIS'], dtype='object')

# DataFrame

La estructura de datos también contiene ejes etiquetados (filas y columnas). Las operaciones aritméticas se alinean en las etiquetas de fila y columna. Puede considerarse como un contenedor tipo diccionario para objetos de serie. La estructura de datos principal de Pandas.


# class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

In [34]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [35]:
#Tenga en cuenta que el tipo inferido es int64.
df.dtypes

col1    int64
col2    int64
dtype: object

In [36]:
# Para aplicar un único tipo de datos:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [38]:
#Construir un DataFrame a partir de un diccionario que incluye Series:
d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
pd.DataFrame(data=d, index=[0, 1, 2, 3])

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

In [39]:
#Construyendo un DataFrame a partir de ndarray numpy:

df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df2

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [41]:
#Construir un DataFrame a partir de un ndarray numpy que tiene columnas etiquetadas:
data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
                dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df3 = pd.DataFrame(data, columns=['c', 'a'])

df3

   c  a
0  3  1
1  6  4
2  9  7

In [42]:
#Construyendo un DataFrame a partir de una clase de datos:
from dataclasses import make_dataclass
Point = make_dataclass("Point", [("x", int), ("y", int)])
pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])

   x  y
0  0  0
1  0  3
2  2  3

## Indice en pandas

El índice (etiquetas de fila) del DataFrame.

El índice de un DataFrame es una serie de etiquetas que identifican cada fila. Las etiquetas pueden ser enteros, cadenas o cualquier otro tipo hash. El índice se utiliza para el acceso y la alineación basados ​​en etiquetas, y se puede acceder o modificar mediante este atributo.

In [46]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Aritra'],
                   'Age': [25, 30, 35],
                   'Location': ['Seattle', 'New York', 'Kona']},
                  index=([10, 20, 30]))
df.index

Index([10, 20, 30], dtype='int64')

En este ejemplo, creamos un DataFrame con 3 filas y 3 columnas, que incluye información de nombre, edad y ubicación. Establecemos las etiquetas de índice con los números enteros 10, 20 y 30. A continuación, accedemos al atributo index del DataFrame, que devuelve un objeto Index que contiene las etiquetas de índice.

In [47]:
df.index = [100, 200, 300]
df

       Name  Age  Location
100   Alice   25   Seattle
200     Bob   30  New York
300  Aritra   35      Kona

En este ejemplo, modificamos las etiquetas de índice del DataFrame asignando una nueva lista de etiquetas al atributo index . El DataFrame se actualiza con las nuevas etiquetas y la salida muestra el DataFrame modificado.

## Columnas en pandas
Las etiquetas de las columnas del DataFrame.

In [48]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df

   A  B
0  1  3
1  2  4

In [ ]:
# El tipo de datos de cada columna.
df = pd.DataFrame({'float': [1.0],
                   'int': [1],
                   'datetime': [pd.Timestamp('20180310')],
                   'string': ['foo']})
df.dtypes

In [50]:
#mprima un resumen conciso de un DataFrame.
# Este método imprime información sobre un DataFrame, incluido el índice dtype y las columnas, los valores no nulos y el uso de memoria.

int_values = [1, 2, 3, 4, 5]
text_values = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
float_values = [0.0, 0.25, 0.5, 0.75, 1.0]
df = pd.DataFrame({"int_col": int_values, "text_col": text_values,
                  "float_col": float_values})
#df
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   int_col    5 non-null      int64
 1   text_col   5 non-null      object
 2   float_col  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

In [51]:
# select_dtypes, Devuelve un subconjunto de las columnas del DataFrame en función de los tipos de columnas.
df = pd.DataFrame({'a': [1, 2] * 3,
                   'b': [True, False] * 3,
                   'c': [1.0, 2.0] * 3})
df

   a      b    c
0  1   True  1.0
1  2  False  2.0
2  1   True  1.0
3  2  False  2.0
4  1   True  1.0
5  2  False  2.0

In [53]:
#df.select_dtypes(include='bool')
#df.select_dtypes(include=['float64'])
#df.select_dtypes(exclude=['int64'])

     c
0  1.0
1  2.0
2  1.0
3  2.0
4  1.0
5  2.0

In [56]:
#Devuelve una representación Numpy del DataFrame.
df = pd.DataFrame({'age':    [ 3,  29],
                   'height': [94, 170],
                   'weight': [31, 115]})
#df
#df.dtypes
df.values

array([[  3,  94,  31],
       [ 29, 170, 115]])

Un DataFrame donde todas las columnas son del mismo tipo (por ejemplo, int64) da como resultado una matriz del mismo tipo.

In [59]:
df2 = pd.DataFrame([('parrot',   24.0, 'second'),
                    ('lion',     80.5, 1),
                    ('monkey', np.nan, None)],
                  columns=('name', 'max_speed', 'rank'))

df2.dtypes
df2.values

array([['parrot', 24.0, 'second'],
       ['lion', 80.5, 1],
       ['monkey', nan, None]], dtype=object)

In [62]:
url = (
    "https://raw.githubusercontent.com/pandas-dev"
    "/pandas/main/pandas/tests/io/data/csv/tips.csv"
)
tips = pd.read_csv(url)
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [65]:
tips[["total_bill", "tip", "smoker", "time"]]

     total_bill   tip smoker    time
0         16.99  1.01     No  Dinner
1         10.34  1.66     No  Dinner
2         21.01  3.50     No  Dinner
3         23.68  3.31     No  Dinner
4         24.59  3.61     No  Dinner
..          ...   ...    ...     ...
239       29.03  5.92     No  Dinner
240       27.18  2.00    Yes  Dinner
241       22.67  2.00    Yes  Dinner
242       17.82  1.75     No  Dinner
243       18.78  3.00     No  Dinner

[244 rows x 4 columns]

In [66]:
# Con pandas, puedes usar el DataFrame.assign()método de un DataFrame para agregar una nueva columna:
tips.assign(tip_rate=tips["tip"] / tips["total_bill"])

     total_bill   tip     sex smoker   day    time  size  tip_rate
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

In [67]:
#Los DataFrames se pueden filtrar de varias maneras; la más intuitiva de las cuales es mediante
tips[tips["total_bill"] > 10]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[227 rows x 7 columns]

In [68]:
# Propinas de más de $5 en las cenas:
tips[(tips["time"] == "Dinner") & (tips["tip"] > 5.00)]

     total_bill    tip     sex smoker  day    time  size
23        39.42   7.58    Male     No  Sat  Dinner     4
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
116       29.93   5.07    Male     No  Sun  Dinner     4
155       29.85   5.14  Female     No  Sun  Dinner     5
170       50.81  10.00    Male    Yes  Sat  Dinner     3
172        7.25   5.15    Male    Yes  Sun  Dinner     2
181       23.33   5.65    Male    Yes  Sun  Dinner     2
183       23.17   6.50    Male    Yes  Sun  Dinner     4
211       25.89   5.16    Male    Yes  Sat  Dinner     4
212       48.33   9.00    Male     No  Sat  Dinner     4
214       28.17   6.50  Female    Yes  Sat  Dinner     3
239       29.03   5.92    Male     No  Sat  Dinner     3

In [69]:
#Propinas para grupos de al menos 5 comensales O la cuenta total fue superior a $45:
tips[(tips["size"] >= 5) | (tips["total_bill"] > 45)]

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
185       20.69   5.00    Male     No   Sun  Dinner     5
187       30.46   2.00    Male    Yes   Sun  Dinner     5
212       48.33   9.00    Male     No   Sat  Dinner     4
216       28.15   3.00    Male    Yes   Sat  Dinner     5

Importar texto de Excel , **read_csvpuede** aceptar varios parámetros para especificar cómo se analizarán los datos. Por ejemplo, si los datos estuvieran delimitados por tabulaciones y no tuvieran nombres de columna, el comando pandas sería:

In [78]:
url = (
    "https://raw.githubusercontent.com/wilmanAQ"
    "/Inteligencia_Artificial/IA/50%20best%20restaurants%20database.csv" # Corrected URL to raw data
)
tips = pd.read_csv(url)
tips

,Ranking,Restaurant,City,Country,Lat,Lon,Stars,Chef,Website,Menu,Currency,Description
0,1,Mirazur,Menton,France,43.785882,7.527998,3.0,Mauro Colagreco,https://www.mirazur.fr/,320,EUR,Argentina’s prime culinary export serves exqui...
1,2,Noma,Copenhagen,Denmark,55.683153,12.610426,2.0,René Redzepi,https://noma.dk/,2800,DKK,The restaurant that coined New Nordic cuisine ...
2,3,Etxebarri,Axpe,Spain,43.115870,-2.600658,1.0,Victor Arguinzoniz,https://asadoretxebarri.com/,200,EUR,"Minimalist, accurate and artful grill cookery ..."
3,4,Gaggan Anand,Bangkok,Thailand,13.739190,100.537440,NaN,Gaggan Anand,https://gaggananand.com/,8000,THB,"A colourful, emoji-led feast from Asia’s unsto..."
4,5,Geranium,Copenhagen,Denmark,55.703755,12.572072,3.0,Rasmus Kofoed,https://www.geranium.dk/en/,2800,DKK,"Detailed, artful plates that celebrate Scandin..."
5,6,Central,Lima,Peru,-12.099300,-77.065000,NaN,Virgilio Martínez and Pía León,https://www.centralrestaurante.com.pe/,480,PEN,A showcase of colour and diversity from all ov...
6,7,Mugaritz,San Sebastian,Spain,43.314798,-1.974583,2.0,Andoni Luis Aduriz,https://www.mugaritz.com/,220,EUR,A string of innovative creations to challenge ...
7,8,Arpège,Paris,France,48.855703,2.317101,3.0,Alain Passard,https://www.alain-passard.com/,420,EUR,Vegetables are given a chance to shine under t...
8,9,Disfrutar,Barcelona,Spain,41.387762,2.153172,2.0,Mateu Casañas,http://www.disfrutarbarcelona.com/,195,EUR,A host of brilliantly conceived surprises deli...
9,10,Maido,Lima,Peru,-12.043180,-77.028240,NaN,Mitsuharu Tsumura and Cesar Choy,http://maido.pe/,349,PEN,Lima favourite fuses Japanese and Peruvian cui...
10,11,Den,Tokyo,Japan,35.670289,139.696816,NaN,Zaiyu Hasegawa,http://www.jimbochoden.com/,17000,JPY,"Japanese cuisine with quality, creativity and ..."
11,12,Pujol,Mexico City,Mexico,19.371422,-99.150344,NaN,Enrique Olvera,https://www.pujol.com.mx/,2500,MXN,Mexico’s most famous chef filters his country’...
12,13,White Rabbit,Moscow,Russia,55.741469,37.615561,NaN,Vladimir Mukhin,https://whiterabbitmoscow.ru/en/,11000,RUB,Boundless creativity with Russian ingredients ...
13,14,Azurmendi,Larrabetzu,Spain,43.265940,-2.818745,3.0,Eneko Atxa,https://www.azurmendi.biz/,250,EUR,Innovative cuisine with sustainability at heart
14,15,Septime,Paris,France,48.853604,2.380832,1.0,Bertrand Grébaut,http://www.septime-charonne.fr/,95,EUR,Explosive flavours and unsung ingredient mashu...
15,16,Alain Ducasse au Plaza Athénée,Paris,France,48.866175,2.304268,3.0,Alain Ducasse with Romain Meder,https://www.dorchestercollection.com/en/paris/...,395,EUR,One of France’s iconic chefs defines his conce...
16,17,Steirereck,Vienna,Austria,48.198674,16.348388,2.0,Heinz Reitbauer,https://www.steirereck.at/en/restaurant/,169,EUR,A futuristic setting showcasing trailblazing A...
17,18,Odette,Singapore,Singapore,1.289739,103.851368,3.0,Julien Royer,https://www.odetterestaurant.com/,358,SGD,Ultra-refined French dining from a new-generat...
18,19,Twins Garden,Moscow,Russia,55.741469,37.615561,NaN,Ivan and Sergey Berezutski,http://twinsgarden.ru/en/,8000,RUB,Superlative home-grown produce presented by Ru...
19,20,Tickets,Barcelona,Spain,41.375217,2.156968,1.0,Fran Agudo,https://elbarri.com/en/restaurant/tickets/,70,EUR,"A carnival of playful tapas delights, where no..."
20,21,Frantzén,Stockholm,Sweden,59.333854,18.058519,3.0,Bjorn Frantzén,https://www.restaurantfrantzen.com/,3500,SEK,The return of Stockholm’s most creative cook s...
21,22,Narisawa,Tokyo,Japan,35.692709,139.699506,NaN,Yoshihiro Narisawa,http://www.narisawa-yoshihiro.com/,38500,JPY,Yoshihiro Narisawa brings nature to the plate ...
22,23,Cosme,New York,USA,40.833200,-73.408320,0.0,Daniela Soto-Innes,https://www.cosmenyc.com/,98,USD,Original Mexican-inspired cuisine from The Wor...
23,24,Quintonil,Mexico City,Mexico,19.430800,-99.150344,NaN,Jorge Vallejo,http://www.quintonil.com/en/,2400,MXN,A taste of pure Mexico from a talented young chef
24,25,Alléno Paris au Pavillon Ledoyen,Paris,France,48.866061,2.315677,3.0,Yannick Alléno,http://www.yannick-alleno.com/,395,EUR,A tour de force of boundary pushing technique ...
25,26,Boragó,Santiago,Chile,-33.428532,-70.630133,NaN,Rodolfo Guzmán,https://www.borago.cl/,85000,CLP,Zero-kilometre sourcing and indigenous ingredi...
26,27,The Clove Club,London,UK,51.527045,-0.079150,1.0,Isaac McHale,https://thecloveclub.com/,145,GBP,Delicious British cuisine from a talented kitc...
27,28,Blue Hill at Stone Barns,Tarrytown,USA,41.102080,-73.828900,2.0,Dan Barber,https://www.bluehillfarm.com/,195,USD,Dan Barber’s progressive rural farm-restaurant...
28,29,Piazza Duomo,Alba,Italy,44.700554,8.035567,3.0,Enrico Crippa,https://www.piazzaduomoalba.it/it/,300,EUR,"Inventive, artistic Italian dishes matched wit..."
29,30,Elkano,Getaria,Spain,43.303043,-2.205062,1.0,Aitor Arregi with Pablo Vicari,https://www.restauranteelkano.com/,110,EUR,A near-perfect example of an authentic Basque ...
30,31,Le Calandre,Rubano,Italy,45.426347,11.790589,3.0,Massimiliano Alajmo,https://www.alajmo.it/it/sezione/le-calandre/l...,240,EUR,Contemporary Italian cuisine at a detail-drive...
31,32,Nerua Guggenheim Bilbao,Bilbao,Spain,43.258534,-2.937123,1.0,Josean Alija,https://www.neruaguggenheimbilbao.com/,148,EUR,Modern art meets Basque masterpiece at the Gug...
32,33,Lyle's,London,UK,51.523764,-0.076932,1.0,James Lowe,https://www.lyleslondon.com/,65,GBP,The epitome of Modern British food in an histo...
33,34,Don Julio,Buenos Aires,Argentina,-34.586200,-58.424400,NaN,Pablo Jesus Rivero with Guido Tassi,http://www.parrilladonjulio.com/,50,USD,Traditional steakhouse showing diners what the...
34,35,Atelier Crenn,San Francisco,USA,37.798370,-122.436045,3.0,Dominique Crenn,https://www.ateliercrenn.com/,335,USD,Poetry-led cuisine from one of San Francisco’s...
35,36,Le Bernardin,New York,USA,40.761403,-73.981719,3.0,Eric Ripert,https://www.le-bernardin.com/,210,USD,Fish-forward superlative French fine dining
36,37,Alinea,Chicago,USA,41.913000,-87.650000,3.0,Grant Achatz with Simon Davies,https://www.alinearestaurant.com/,365,USD,Artistic modernist cuisine built from the worl...
37,38,Hiša Franko,Kobarid,Slovenia,46.247004,13.536430,2.0,Ana Roš,https://www.hisafranko.com/,175,EUR,Slovenia’s top chef serves superlative local p...
38,39,A Casa do Porco,Sao Paulo,Brazil,-23.545000,-46.646000,0.0,Jefferson Rueda,https://acasadoporco.com.br/,139,BRL,An homage to the hog from São Paulo’s most cre...
39,40,Restaurant Tim Raue,Berlin,Germany,52.520450,13.407320,2.0,Tim Raue,https://tim-raue.com/,218,EUR,Asian-tinted perfection from the charismatic B...
40,41,The Chairman,Hong Kong,Hong Kong,22.284600,114.150500,0.0,Kwok Keung Tung with Danny Yip,http://www.thechairmangroup.com/,700,HKD,"Seasonal, ingredient-driven Cantonese cuisine ..."
41,42,Belcanto,Lisbon,Portugal,38.710010,-9.141430,2.0,José Avillez,https://belcanto.pt/index.php,185,EUR,Letting Lisbon’s true culinary colours show
42,43,Hof Van Cleve,Kruisem,Belgium,50.903570,3.509568,3.0,Peter Goossens,https://hofvancleve.com/,345,EUR,Pitch-perfect plates in pastoral surrounds by ...
43,44,The Test Kitchen,Cape Town,South Africa,-33.927582,18.457066,NaN,Luke Dale-Roberts,https://www.thetestkitchen.co.za/,895,ZAR,A treat for the senses with light and dark mel...
44,45,Sühring,Bangkok,Thailand,13.710800,100.543200,2.0,Thomas and Mathias Sühring,http://restaurantsuhring.com/,5000,THB,Cool and collected contemporary German cuisine...
45,46,De Librije,Zwolle,The Netherlands,52.515365,6.097879,3.0,Jonnie Boer,https://www.librije.com/,253,EUR,Charismatic duo serving modern Dutch food in a...
46,47,Benu,San Francisco,USA,37.785436,-122.399214,3.0,Corey Lee,https://www.benusf.com/,325,USD,A sophisticated confluence of culinary culture...
47,48,Ultraviolet,Shanghai,China,31.246027,121.472000,3.0,Paul Pairet,https://uvbypp.cc/,600,USD,"The ultimate in immersive, multi-sensory dining"
48,49,Leo,Bogotà,Colombia,4.609710,-74.081750,NaN,Leonor Espinosa,http://www.restauranteleo.com/,100,USD,Inventive and perfectly presented Colombian cu...
49,50,Schloss Schauenstein,Furstenau,Switzerland,46.722102,9.448301,3.0,Andreas Caminada,https://schauenstein.ch/,270,CHF,A fairy tale dining experience built on the fo...

In [79]:
pd.read_csv("/content/exported_data.csv")

,Unnamed: 0,Category,Serving Size (g),Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbohydrates (g),Dietary Fiber (g),Sugars (g),Protein (g),Vitamin A % DV,Vitamin C % DV,Calcium % DV,Iron % DV
0,BBQ Rib,Sandwich,208,580,31.0,10.0,0.0,60,1260,54,3,18,21,8,4,4,20
1,Black Forest Ham,Sandwich,219,260,4.0,1.5,0.0,30,720,42,5,8,18,30,15,4,15
2,Chicken & Bacon Ranch Melt,Sandwich,284,530,26.0,10.0,0.5,100,1100,41,3,6,36,40,25,20,20
3,Chicken Mango Curry,Sandwich,234,330,7.0,1.5,0.0,50,840,43,3,9,24,15,20,2,25
4,Chicken Tikka,Sandwich,205,290,5.0,1.0,0.0,50,720,39,2,6,23,10,10,0,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Red Onions,Veggies,7,0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0
131,Spinach,Veggies,7,0,0.0,0.0,0.0,0,5,0,0,0,0,15,2,0,0
132,Tomatoes,Veggies,35,5,0.0,0.0,0.0,0,0,1,0,1,0,10,4,0,0
133,Bacon,Protein,15,70,6.0,2.0,0.0,15,250,1,0,1,5,0,6,0,0
134,Parmesan Cheese,Seasonings,1,5,0.0,0.0,0.0,0,25,0,0,0,1,0,0,0,0

In [81]:
tips_df = pd.read_excel("/content/futbolargentino.xlsx", index_col=0)
tips_df

,Jugadores,Posicion,Edad,Altura,Pie,Fichado,Equipo Anterior,Valor de mercado,Temporada,Club
1.0,Nicolás Gianni,Centrocampista,25,1.75,derecho,01/07/2000,Inferiores Argentinos Juniors,800000,2008.0,Argentinos Juniors
2.0,Maximiliano Sola,Defensa,22,1.8,izquierdo,-,NaN,-,2008.0,Argentinos Juniors
3.0,Nicolás Navarro,Portero,23,1.9,derecho,24/07/2010,SSC Nápoles,2000000,2008.0,Argentinos Juniors
4.0,Juan Carrera,Portero,27,1.91,derecho,01/01/2005,inactivo,800000,2008.0,Argentinos Juniors
5.0,Sebastián Torrico,Portero,28,1.86,derecho,01/01/2009,CD Godoy Cruz Antonio Tomba,250000,2008.0,Argentinos Juniors
...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN